<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="MidiTimecode" />
    <Using Include="MidiTimecode.Messages" />
    <Using Include="MidiTimecode.Cueing" />
    <Using Include="MidiTimecode.Sync" />
    <Using Include="MidiTimecode.Describe" />
    <ProjectReference Include="../../src/MidiTimecode/MidiTimecode.csproj" />
  </ItemGroup>
</Project>
